/*
-- Query: SELECT * FROM collaboration.quottimes
-- Date: 2022-03-14 21:10
*/
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (1,1,'Numquam est.','Repellendus eos at numquam optio. Minus iure hic facilis dolorum dolorum debitis. Repellendus aliquam laboriosam qui voluptas facilis distinctio corporis.',NULL,'2022-03-14 06:14:13','2022-03-14 06:14:13');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (2,2,'Hic in.','Veniam autem ad adipisci rerum tempore fugit aut. Libero libero dolorem delectus inventore eum eius. Non velit rem at aliquid alias sunt id. Autem officia accusamus aut impedit eos quisquam. In sed rerum facilis reiciendis voluptatem.',NULL,'2022-03-14 06:14:13','2022-03-14 06:14:13');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (3,6,'Ducimus.','Cum minima dolores sit maiores. Eligendi ut doloribus odit pariatur dolores. Qui et vitae ut.',NULL,'2022-03-14 06:14:13','2022-03-14 06:14:13');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (4,5,'Et tempore et.','Sint libero fugiat sequi veniam ab molestiae. Quia suscipit aliquid dolor at. Non culpa qui reprehenderit quia. Totam non ut accusamus voluptatem quis.',NULL,'2022-03-14 06:14:13','2022-03-14 06:14:13');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (5,6,'Sed nihil.','Architecto magni et cupiditate libero velit. Quas aut voluptatibus quae natus libero hic voluptas. Rerum dolor dolorem rerum eaque. Placeat alias pariatur laboriosam natus voluptates accusamus.',NULL,'2022-03-14 06:14:13','2022-03-14 06:14:13');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (6,4,'Quia et.','Illo accusantium rerum qui vero qui quis. Deleniti omnis porro ullam omnis nobis dicta soluta. Repudiandae aut corporis omnis qui porro amet earum iste.',NULL,'2022-03-14 06:14:13','2022-03-14 06:14:13');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (7,5,'Qui praesentium.','Voluptatibus fuga rerum quibusdam voluptatum. Id quidem quod facilis enim consectetur dignissimos sed. Deserunt non natus illum possimus illum. Consequatur blanditiis et possimus veniam aut.',NULL,'2022-03-14 06:14:13','2022-03-14 06:14:13');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (8,1,'Error nostrum id.','Iste molestias magni autem dolores quae. Ducimus iusto provident dolore magnam. Commodi laboriosam vero qui sint eligendi omnis eum.',NULL,'2022-03-14 06:14:13','2022-03-14 06:14:13');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (9,1,'Libero accusamus.','Consequatur omnis laboriosam aut consequatur quibusdam recusandae quos. Impedit autem quo molestiae sit. Labore eos quis dolore quasi dolor consectetur ea sed.',NULL,'2022-03-14 06:14:13','2022-03-14 06:14:13');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (10,1,'Deleniti beatae.','Est est ipsum cupiditate rerum consequatur amet labore. Eos laborum id repellat eligendi sed nesciunt quia sunt. A fugiat hic voluptas est pariatur. Architecto deserunt ex incidunt tempore.',NULL,'2022-03-14 06:14:13','2022-03-14 06:14:13');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (11,3,'Quam qui.','Ratione accusamus sit sint in omnis voluptates. Dolor quas sunt alias molestiae facilis. Tempora sit nesciunt repudiandae est repellat ipsum.',NULL,'2022-03-14 06:21:53','2022-03-14 06:21:53');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (12,5,'Nobis est esse.','Assumenda ad eius enim. Beatae libero in modi deserunt quod molestias error. Tempore corrupti praesentium dolor in.',NULL,'2022-03-14 06:21:53','2022-03-14 06:21:53');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (13,3,'Odit.','Dicta consequatur et exercitationem qui doloribus officia. Voluptas alias omnis accusantium doloribus nesciunt quam cum. Aut ratione ea recusandae qui.',NULL,'2022-03-14 06:21:53','2022-03-14 06:21:53');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (14,6,'Eveniet quia quia.','Sed sit veritatis magni aspernatur. Deserunt neque voluptatem id id sed aut sit vel. Nam iste et placeat fugit aut saepe. Inventore quo error quod atque culpa debitis et sunt.',NULL,'2022-03-14 06:21:53','2022-03-14 06:21:53');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (15,6,'Quod beatae.','Dolore porro consequatur cum eius sequi. Est quia natus quia eligendi esse dolorem.',NULL,'2022-03-14 06:21:53','2022-03-14 06:21:53');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (16,5,'Et.','Neque et et mollitia porro quia ducimus est. Provident sed quae maiores vero. Provident voluptates ut in ut quod. Cupiditate animi ut cum eveniet error perferendis.',NULL,'2022-03-14 06:21:53','2022-03-14 06:21:53');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (17,6,'Dolorem repellat.','Non dolores tempora sit et. Rerum ratione dignissimos temporibus quibusdam. Natus numquam cum voluptas et ratione alias aliquid reprehenderit. Eligendi dolorem et delectus nihil.',NULL,'2022-03-14 06:21:53','2022-03-14 06:21:53');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (18,4,'Ut voluptatibus.','Voluptates nisi est rerum sapiente est et rem. Sit libero ipsa non excepturi. Aut quod laudantium hic nemo consequuntur et quam.',NULL,'2022-03-14 06:21:53','2022-03-14 06:21:53');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (19,6,'Dolore dolor est.','Et sapiente perferendis qui distinctio. Adipisci repudiandae incidunt incidunt molestias. In ducimus ratione praesentium rerum fugit assumenda error. Laboriosam qui aperiam eum est eos nostrum qui.',NULL,'2022-03-14 06:21:54','2022-03-14 06:21:54');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (20,2,'person','Eaque assumenda excepturi rerum et. Est possimus ipsam non ipsa labore dolor. Sunt qui alias in dolores. Id similique similique sapiente eveniet eius.',NULL,'2022-03-14 06:21:54','2022-03-14 06:21:54');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (21,6,'Nostrum qui.','Accusamus iusto et eveniet accusamus. Voluptatem tempora rem harum. Esse molestias nihil vel in corrupti. Accusantium reprehenderit vel ut in harum.',NULL,'2022-03-14 13:29:44','2022-03-14 13:29:44');
INSERT INTO `` (`id`,`user_id`,`gambar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (22,3,'Aut alias.','Quia blanditiis non nihil. Pariatur et et sit ab consequatur repudiandae. Fugit ad dolore perspiciatis. Ut omnis cumque molestiae sequi temporibus.',NULL,'2022-03-14 13:32:46','2022-03-14 13:32:46');
