/*
-- Query: SELECT * FROM collaboration.quottimes
-- Date: 2022-04-11 21:06
*/
INSERT INTO `` (`id`,`user_id`,`gambar`,`tagar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (1,1,'gambar/CKtJ0NcDoDLAa7pscVrqvVzm8hSurMkNoWna04Ya.jpg','Voluptas.','Non qui temporibus quis dolore dolor. Aperiam earum est beatae eos amet cumque. Adipisci quia dolores quo sed blanditiis. Ducimus voluptates reprehenderit sapiente nulla aut at non. Quisquam nesciunt veritatis consequatur enim earum.',NULL,'2022-04-04 13:18:37','2022-04-11 04:33:45');
INSERT INTO `` (`id`,`user_id`,`gambar`,`tagar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (2,2,'Quasi fugit.','Tenetur dolores ea ut.','Nihil non sed iste voluptas similique quis. Quod eos temporibus qui voluptas asperiores ut aliquid nisi. Cupiditate deserunt omnis nam voluptatum sit. Iure laborum sed praesentium enim similique repellendus.',NULL,'2022-04-04 13:18:37','2022-04-04 13:18:37');
INSERT INTO `` (`id`,`user_id`,`gambar`,`tagar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (4,6,'Voluptates dignissimos.','Ab earum qui at.','Molestiae sed aliquam dolorem. Ipsa ut nihil saepe ea in perferendis consequuntur. Laudantium harum cupiditate vitae quisquam velit. Eligendi et consectetur eaque assumenda voluptatum nemo non quo. Ut sit autem ipsa est necessitatibus.',NULL,'2022-04-04 13:18:37','2022-04-04 13:18:37');
INSERT INTO `` (`id`,`user_id`,`gambar`,`tagar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (5,6,'Ea.','Aliquid est eius.','Consectetur ipsa magni corporis rerum iste ratione. Sunt ut et aut voluptatibus aut voluptas. Natus et quidem laudantium autem. Omnis itaque voluptatem ex minus.',NULL,'2022-04-04 13:18:38','2022-04-04 13:18:38');
INSERT INTO `` (`id`,`user_id`,`gambar`,`tagar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (8,5,'Autem quisquam.','Accusantium et amet.','Dolore assumenda dolores asperiores et et. Incidunt voluptas fuga sit maiores amet ducimus. Dolore quia velit neque quos deserunt excepturi labore. Harum facere nisi cumque ab.',NULL,'2022-04-04 13:18:38','2022-04-04 13:18:38');
INSERT INTO `` (`id`,`user_id`,`gambar`,`tagar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (9,4,'Molestiae.','Maiores ipsum.','Voluptate blanditiis quaerat voluptatem quis. Est ut placeat minima nostrum sit dicta. Vel sequi facere sint vitae.',NULL,'2022-04-04 13:18:38','2022-04-04 13:18:38');
INSERT INTO `` (`id`,`user_id`,`gambar`,`tagar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (10,5,'Aspernatur sit esse.','Ad voluptatem in.','Molestias eveniet eveniet enim nisi. Et molestiae et qui unde. Qui nam similique facere dignissimos.',NULL,'2022-04-04 13:18:38','2022-04-04 13:18:38');
INSERT INTO `` (`id`,`user_id`,`gambar`,`tagar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (11,2,'Modi.','Perspiciatis deleniti.','Voluptate enim aut sint. Eveniet incidunt neque eveniet consequuntur reprehenderit sunt nihil. Totam est id velit sequi ut. Sapiente molestiae accusantium iusto nemo qui libero.',NULL,'2022-04-04 13:18:38','2022-04-04 13:18:38');
INSERT INTO `` (`id`,`user_id`,`gambar`,`tagar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (12,2,'Esse sit.','Reprehenderit similique consequatur.','Porro qui tenetur amet enim et qui vel. Autem architecto mollitia sequi at sed vitae perspiciatis. Unde velit in minima eius totam eveniet placeat. Magnam consectetur libero alias dolore omnis blanditiis ea autem.',NULL,'2022-04-04 13:18:38','2022-04-04 13:18:38');
INSERT INTO `` (`id`,`user_id`,`gambar`,`tagar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (13,1,'gambar/i3lxl76ASc4ILoWfEClSaOhpaJZvlPOHtBnHLUER.jpg','JanganLupaBelajar','Belajar <strong>ngoding</strong> itu bukan cuma <del>sekali</del>, tapi <em>setiap hari</em>',NULL,'2022-04-04 13:25:33','2022-04-04 14:55:41');
INSERT INTO `` (`id`,`user_id`,`gambar`,`tagar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (14,1,'gambar/jTXksZpgeKqemGdrrjVYW3CoDRDKB0Isj0voxnnR.png','nikmati_prosesmu','Ngoding itu seru, kitanya aja yang belum tau',NULL,'2022-04-04 13:41:44','2022-04-04 13:41:44');
INSERT INTO `` (`id`,`user_id`,`gambar`,`tagar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (15,1,'gambar/zeMe8cKMX0wUOWExOoQQcwIPJ3Lr43v5VjXD9N8c.png','tawaAjaDulu','Ekspresi lu ketika program berhasil di run',NULL,'2022-04-04 13:45:40','2022-04-04 13:45:40');
INSERT INTO `` (`id`,`user_id`,`gambar`,`tagar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (16,1,'gambar/feRr13VOMLiC2Ikxy3ZIp1q9lvpWRTDOVzJC4eLD.png','Brewok Man','<strong>Jangan mau kalah sama brewok, mereka aja semangat untuk tumbuh, masa kamu engga</strong>',NULL,'2022-04-04 13:55:32','2022-04-04 13:55:32');
INSERT INTO `` (`id`,`user_id`,`gambar`,`tagar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (17,1,'gambar/Kp6UwRryLksyjBVWcMBjZ1sw8hhg5BtKtTSQn0hz.jpg','j.a.n.g.a.n.t.a.k.u.t','<strong>Keahlian&nbsp;</strong>akan berkembang seiring banyaknya kesalahan',NULL,'2022-04-04 14:12:53','2022-04-04 14:12:53');
INSERT INTO `` (`id`,`user_id`,`gambar`,`tagar`,`isi`,`published_at`,`created_at`,`updated_at`) VALUES (18,3,'gambar/6HFRtplGWUs9zJEo1pmPbsjD4pbdkkPNCWxutclF.jpg','Waktu','<strong>Luangkanlah waktu untuk belajar meski hanya satu jam perhari</strong>',NULL,'2022-04-04 14:19:16','2022-04-04 14:23:12');
